services:
  testmcserver:
    build:
      context: .
      dockerfile: Dockerfile.dynmap
    image: mf-test-mc-server-with-dynmap
    container_name: mf-test-mc-server-with-dynmap
    ports:
      - "25565:25565"
      - "8123:8123"