services:
  testmcserver:
    build: .
    image: mf-test-mc-server
    container_name: mf-test-mc-server
    ports:
      - "25565:25565"
      - "8123:8123"
      - "8100:8100"
    volumes:
      - ./testmcserver:/testmcserver
    environment:
      - MINECRAFT_VERSION=${MINECRAFT_VERSION}
      - OPERATOR_UUID=${OPERATOR_UUID}
      - OPERATOR_NAME=${OPERATOR_NAME}
      - OPERATOR_LEVEL=${OPERATOR_LEVEL}
      - OVERWRITE_EXISTING_SERVER=${OVERWRITE_EXISTING_SERVER}
      - CURRENCIES_ENABLED=${CURRENCIES_ENABLED}
      - DYNMAP_ENABLED=${DYNMAP_ENABLED}
      - BLUEMAP_ENABLED=${BLUEMAP_ENABLED}
      - PLACEHOLDER_API_ENABLED=${PLACEHOLDER_API_ENABLED}