name: MedievalFactions
authors:
- DanTheTechMan
- Pasarus
- Caibinus
- Callum
- Richardhyy
- Mitras2
- Kaonami
- GoodLucky777
- Elafir
- Deej
- VoChiDanh
- alyphen
version: @version@
main: com.dansplugins.factionsystem.MedievalFactions
api-version: 1.13
softdepend: [dynmap, PlaceholderAPI, rpk-notification-lib-bukkit, Mailboxes]
description: Allows players to organise themselves into feudal, diplomatic, lawful groups akin to nations.
commands:
  medievalfactions:
    description: |
      Medieval Factions base command
    aliases: [mf]
    usage: /<command>
  faction:
    description: |
      Faction management command
      /f help - View a list of helpful commands.
      /f ally [faction] - Ally with a faction
      /f breakalliance [faction] - Break alliance with a faction
      /f declarewar [faction] - Declares war on a faction
      /f makepeace [faction] - Requests to make peace with a faction
      /f create [name] - Create a faction with the given name
      /f invite [player] - Invite a player to your faction
      /f join [faction] - Joins a faction you have been invited to
      /f law add [law] - Create a law for your faction
      /f law list - List your faction's laws
      /f law remove [id] - Remove a law from your faction
      /f role view [role] - Views a role
      /f role setpermission [role] [permission] [value] - Sets a permission for a role
      /f role list - Lists roles
      /f role set [player] [role] - Sets a player to a given role
      /f list - Lists factions
      /f claim (radius) - Claims land
      /f power - Views power stats
      /f who - Views a player's faction
      /f disband - Disbands your faction
      /f invoke [ally] [enemy] - Invokes a faction into war
      /f leave - Leaves your faction
    aliases: [f, fraktion, faccion, faccao, фракция, ф]
    usage: /<command> [help|ally|breakalliance|declarewar|makepeace|create|invite|join|law|role|list|claim|power|who|invoke|leave]
permissions:
  mf.help:
    description: View a list of helpful commands.
    default: true
  mf.ally:
    description: Allows allying with other factions
    default: true
  mf.breakalliance:
    description: Allows breaking alliances with other factions
    default: true
  mf.create:
    description: Allows the creation of factions
    default: true
  mf.declarewar:
    description: Allows declaring war on other factions
    default: true
  mf.invite:
    description: Allows inviting players to your faction
    default: true
  mf.join:
    description: Allows joining factions
    default: true
  mf.addlaw:
    description: Allows adding laws
    default: true
  mf.laws:
    description: Allows listing the laws of your faction
    default: true
  mf.removelaw:
    description: Allows removing laws
    default: true
  mf.makepeace:
    description: Allows making peace with other factions
    default: true
  mf.role.view:
    description: Allows viewing roles
    default: true
  mf.role.list:
    description: Allows listing roles
    default: true
  mf.role.setpermission:
    description: Allows setting role permissions
    default: true
  mf.role.set:
    description: Allows setting a faction member's role
    default: true
  mf.list:
    description: Allows listing factions
    default: true
  mf.claim:
    description: Allows claiming land
    default: true
  mf.power:
    description: Allows viewing power
    default: true
  mf.who:
    description: Allows viewing which faction a player is part of
    default: true
  mf.disband:
    description: Allows disbanding your faction
    default: true
  mf.invoke:
    description: Allows invoking another faction into war
    default: true
  mf.leave:
    description: Allows you to leave your faction
    default: true
  mf.rename:
    description: Allows you to rename your faction
    default: true